import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@src/components/header";
import Footer from "@src/components/footer";
import MainContainer from "@src/components/main-container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pokémon Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} max-w-screen-xl min-h-screen mx-auto p-5 flex flex-col justify-between bg-blue-50 gap-8`}
      >
        <Header />
        <MainContainer>{children}</MainContainer>
        <Footer />
      </body>
    </html>
  );
}
